### ISSUE TITLE
The ability to attach stories to hubs

### ISSUE THREAD

**Issue by crowdcoverllc** [maphubs/maphubs#61]

**Comment by kriscarle** [comment]
I think we need to discuss more to determine exactly what this means. We can add an option to  transfer a user story from a user account to a hub.  In that scenario the hub takes ownership of the story and it is no longer listed under the user's account. This workflow would allow a user that started making content just under their account to later migrate to a hub.

The other option is to change our permissions model so that stories are only ever owned/modified by a single user, and are simply linked by a hub. This would mean that hub administrators would no longer be fully in control of content on the hub. They can choose to include a story, but cannot modify the story (or prevent the story from being modified after it is listed under the hub). This is more along the lines of Medium's upcoming "Collections" feature https://medium.com/talkback/introducing-medium-collections-175bfb29386f#.mpnu0oalc
